# Generated by Django 6.0 on 2025-12-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_category_blogpost_contactmessage_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='managed_by',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
