# Generated by Django 6.0 on 2025-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
