# Generated by Django 6.0 on 2026-01-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
